spring:
  application:
    name: reminder
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost/reminders
    username: postgres
    password: rooot
    driver-class-name: org.postgresql.Driver
  quartz:
    job-store-type: jdbc
